{% set version = "5.0.2" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}
{% set abi_version = "5.0" %}

package:
  name: libxmlpp
  version: {{ version }}

source:
  fn: libxml++-{{ version }}.tar.xz
  url: http://ftp.gnome.org/pub/GNOME/sources/libxml++/{{ major_minor }}/libxml++-{{ version }}.tar.xz
  sha256: 7c17cc3e5a2214314dee5a1354f4b436f266ded6185232a0534f352a76240d5a

build:
  number: 0
  run_exports:
    - libxmlpp-{{ abi_version }} >={{ version }}

outputs:
  - name: libxmlpp-{{ abi_version }}
    script: build_libxmlpp.sh  # [unix]
    script: build_libxmlpp.bat  # [win]
    build:
      run_exports:
        - libxmlpp-{{ abi_version }} >={{ version }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - xz
        - meson
        - ninja
        - pkg-config
      host:
        - zlib
        - libxml2
        - glib
        - glibmm
      run_constrained:
        - libxmlpp {{ version }}
    test:
      requires:
        - pkg-config
        - glib
      commands:
        - test -f ${PREFIX}/lib/libxml++-{{ abi_version }}${SHLIB_EXT}  # [unix]
        - if not exist %LIBRARY_BIN%\\xml++-vc142-{{ abi_version }}-1.dll exit 1  # [win]
        - pkg-config --exact-version {{ version }} libxml++-{{ abi_version }}
  - name: libxmlpp
    requirements:
      run:
        - libxmlpp-{{ abi_version }} {{ version }}
    test:
      requires:
        - pkg-config
      commands:
        - test -f ${PREFIX}/lib/pkg-config/libxml++-{{ abi_version }}.pc # [unix]
        - if not exist %LIBRARY_LIB%\\pkgconfig\\libxml++-{{ abi_version }}.pc exit 1 # [win]


about:
  home: https://libxmlplusplus.github.io/libxmlplusplus/
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: C++ bindings for libxml2

extra:
  recipe-maintainers:
    - scopatz
